version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - run: 
        name: Build and compile files
        command: |
          npm install
          npm run build
  deploy:
    docker:
        - image: cimg/base:2023.03
    steps:
      - run:
        name: Deploy via FTP
        command: |
          sudo apt-get update
          sudo apt-get install -y lftp

# Orchestrate our job run sequence
workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
